server:
  address: "0.0.0.0:8083"
#  mode: "release"
  down_time: 10
  max_body_size: 1
  request_timeout: 5

database:
  host: "localhost"
  port: 3306
  user: "root"
  password: "password"
  name: "mydatabase"

